"""Python client for VWorld HTTP APIs."""

from .catalog import DATA_SERVICE_BY_ID, DATA_SERVICES, DataService, get_data_service
from .client import VworldClient
from .exceptions import (
    VworldAuthError,
    VworldError,
    VworldInvalidParameterError,
    VworldNetworkError,
    VworldNoDataError,
    VworldRateLimitError,
    VworldServerError,
)
from .models import (
    AddressCategory,
    AddressType,
    BBox,
    BBoxLike,
    BinaryResponse,
    Crs,
    DistrictCategory,
    ImageFormat,
    LatLon,
    LegendType,
    LonLat,
    PointLike,
    ReverseGeocodeType,
    SearchType,
    StaticMapBase,
    TextResponse,
    TileLayer,
    bbox_from_latlon,
    latlon,
    lonlat,
)

__all__ = [
    "DATA_SERVICE_BY_ID",
    "DATA_SERVICES",
    "AddressCategory",
    "AddressType",
    "BBox",
    "BBoxLike",
    "BinaryResponse",
    "Crs",
    "DataService",
    "DistrictCategory",
    "ImageFormat",
    "LatLon",
    "LegendType",
    "LonLat",
    "PointLike",
    "ReverseGeocodeType",
    "SearchType",
    "StaticMapBase",
    "TextResponse",
    "TileLayer",
    "VworldAuthError",
    "VworldClient",
    "VworldError",
    "VworldInvalidParameterError",
    "VworldNetworkError",
    "VworldNoDataError",
    "VworldRateLimitError",
    "VworldServerError",
    "bbox_from_latlon",
    "get_data_service",
    "latlon",
    "lonlat",
]
