"""Python client for VWorld HTTP APIs."""

from .catalog import DATA_SERVICE_BY_ID, DATA_SERVICES, DataService, get_data_service
from .client import VworldClient
from .exceptions import (
    VworldAuthError,
    VworldError,
    VworldInvalidParameterError,
    VworldNetworkError,
    VworldNoDataError,
    VworldRateLimitError,
    VworldServerError,
)
from .metadata import (
    VworldResponseMetadata,
    make_cache_key,
    make_response_metadata,
    raw_to_json_safe,
    redact_credentials_in_text,
    request_params_from_url,
    sanitize_request_params,
    to_json_safe_raw,
)
from .models import (
    AddressCategory,
    AddressType,
    BBox,
    BBoxLike,
    BinaryResponse,
    Crs,
    DistrictCategory,
    ImageFormat,
    LatLon,
    LegendType,
    LonLat,
    PointLike,
    ReverseGeocodeType,
    SearchType,
    StaticMapBase,
    TextResponse,
    TileLayer,
    bbox_from_latlon,
    latlon,
    lonlat,
)
from .pagination import (
    VworldPageInfo,
    has_next_page,
    iter_pages,
    next_page_no,
    response_items,
    response_page_info,
    response_root,
    response_status,
)

__all__ = [
    "DATA_SERVICE_BY_ID",
    "DATA_SERVICES",
    "AddressCategory",
    "AddressType",
    "BBox",
    "BBoxLike",
    "BinaryResponse",
    "Crs",
    "DataService",
    "DistrictCategory",
    "ImageFormat",
    "LatLon",
    "LegendType",
    "LonLat",
    "PointLike",
    "ReverseGeocodeType",
    "SearchType",
    "StaticMapBase",
    "TextResponse",
    "TileLayer",
    "VworldAuthError",
    "VworldClient",
    "VworldError",
    "VworldInvalidParameterError",
    "VworldNetworkError",
    "VworldNoDataError",
    "VworldPageInfo",
    "VworldRateLimitError",
    "VworldResponseMetadata",
    "VworldServerError",
    "bbox_from_latlon",
    "get_data_service",
    "has_next_page",
    "iter_pages",
    "latlon",
    "lonlat",
    "make_cache_key",
    "make_response_metadata",
    "next_page_no",
    "raw_to_json_safe",
    "redact_credentials_in_text",
    "request_params_from_url",
    "response_items",
    "response_page_info",
    "response_root",
    "response_status",
    "sanitize_request_params",
    "to_json_safe_raw",
]
